"""Schemas for report generation."""

from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class ReportType(str, Enum):
    """Type of report."""

    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"
    QUARTERLY = "QUARTERLY"
    ANNUAL = "ANNUAL"
    CUSTOM = "CUSTOM"


class ReportPeriod(str, Enum):
    """Report period type."""

    DAY = "DAY"
    WEEK = "WEEK"
    MONTH = "MONTH"
    QUARTER = "QUARTER"
    YEAR = "YEAR"


class ReportStatus(str, Enum):
    """Report generation status."""

    PENDING = "PENDING"
    GENERATING = "GENERATING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"


class ExportFormat(str, Enum):
    """Report export format."""

    PDF = "PDF"
    EXCEL = "EXCEL"
    CSV = "CSV"
    JSON = "JSON"


class ReportConfig(BaseModel):
    """Configuration for report generation."""

    include_nav_chart: bool = Field(default=True, description="Include NAV chart")
    include_allocation_chart: bool = Field(
        default=True, description="Include allocation chart"
    )
    include_risk_summary: bool = Field(default=True, description="Include risk summary")
    include_flow_analysis: bool = Field(
        default=True, description="Include flow analysis"
    )
    include_recommendations: bool = Field(
        default=True, description="Include recommendations"
    )
    default_format: ExportFormat = Field(
        default=ExportFormat.PDF, description="Default export format"
    )


class ReportMetadata(BaseModel):
    """Report metadata."""

    report_id: str = Field(..., description="Unique report ID")
    report_type: ReportType = Field(..., description="Report type")
    period_start: date = Field(..., description="Period start date")
    period_end: date = Field(..., description="Period end date")
    generated_at: datetime = Field(..., description="Generation timestamp")
    generated_by: str = Field(default="system", description="Generated by")
    status: ReportStatus = Field(..., description="Report status")
    format: ExportFormat = Field(..., description="Export format")
    file_size_bytes: int | None = Field(None, description="File size")
    storage_path: str | None = Field(None, description="Storage path")


class NavSummary(BaseModel):
    """NAV summary for reports."""

    start_nav: Decimal = Field(..., description="NAV at period start")
    end_nav: Decimal = Field(..., description="NAV at period end")
    high_nav: Decimal = Field(..., description="Highest NAV")
    low_nav: Decimal = Field(..., description="Lowest NAV")
    change_value: Decimal = Field(..., description="NAV change value")
    change_percent: Decimal = Field(..., description="NAV change %")
    volatility: Decimal = Field(..., description="Period volatility")


class FlowSummary(BaseModel):
    """Flow summary for reports."""

    total_subscriptions: Decimal = Field(..., description="Total subscriptions")
    total_redemptions: Decimal = Field(..., description="Total redemptions")
    net_flow: Decimal = Field(..., description="Net flow")
    subscription_count: int = Field(..., description="Subscription count")
    redemption_count: int = Field(..., description="Redemption count")
    avg_subscription_size: Decimal = Field(..., description="Average subscription")
    avg_redemption_size: Decimal = Field(..., description="Average redemption")


class RiskSummary(BaseModel):
    """Risk summary for reports."""

    avg_risk_score: int = Field(..., description="Average risk score")
    max_risk_score: int = Field(..., description="Maximum risk score")
    risk_level_distribution: dict[str, int] = Field(
        ..., description="Days at each risk level"
    )
    alerts_generated: int = Field(..., description="Alerts generated")
    alerts_resolved: int = Field(..., description="Alerts resolved")
    emergencies_triggered: int = Field(..., description="Emergencies triggered")


class AllocationSummary(BaseModel):
    """Allocation summary for reports."""

    tier_allocations: dict[str, Decimal] = Field(..., description="Tier allocations")
    top_assets: list[dict[str, Any]] = Field(..., description="Top assets")
    rebalances_executed: int = Field(..., description="Rebalances executed")
    total_rebalance_value: Decimal = Field(..., description="Total rebalanced")


class DailyReport(BaseModel):
    """Daily report."""

    metadata: ReportMetadata = Field(..., description="Report metadata")
    report_date: date = Field(..., description="Report date")

    # NAV
    opening_nav: Decimal = Field(..., description="Opening NAV")
    closing_nav: Decimal = Field(..., description="Closing NAV")
    nav_change: Decimal = Field(..., description="NAV change")
    nav_change_percent: Decimal = Field(..., description="NAV change %")

    # AUM
    opening_aum: Decimal = Field(..., description="Opening AUM")
    closing_aum: Decimal = Field(..., description="Closing AUM")
    aum_change: Decimal = Field(..., description="AUM change")

    # Flows
    subscriptions: Decimal = Field(..., description="Day subscriptions")
    redemptions: Decimal = Field(..., description="Day redemptions")
    net_flow: Decimal = Field(..., description="Net flow")
    subscription_count: int = Field(..., description="Subscription count")
    redemption_count: int = Field(..., description="Redemption count")

    # Risk
    risk_score: int = Field(..., description="End-of-day risk score")
    risk_level: str = Field(..., description="Risk level")
    active_alerts: int = Field(..., description="Active alerts")

    # Allocation
    l1_allocation: Decimal = Field(..., description="L1 allocation %")
    l2_allocation: Decimal = Field(..., description="L2 allocation %")
    l3_allocation: Decimal = Field(..., description="L3 allocation %")

    # Notes
    highlights: list[str] = Field(default_factory=list, description="Key highlights")
    concerns: list[str] = Field(default_factory=list, description="Concerns")


class WeeklyReport(BaseModel):
    """Weekly report."""

    metadata: ReportMetadata = Field(..., description="Report metadata")
    week_number: int = Field(..., description="Week number")
    year: int = Field(..., description="Year")

    # Summary sections
    nav_summary: NavSummary = Field(..., description="NAV summary")
    flow_summary: FlowSummary = Field(..., description="Flow summary")
    risk_summary: RiskSummary = Field(..., description="Risk summary")
    allocation_summary: AllocationSummary = Field(..., description="Allocation summary")

    # Performance
    weekly_return: Decimal = Field(..., description="Weekly return")
    mtd_return: Decimal = Field(..., description="Month-to-date return")
    ytd_return: Decimal = Field(..., description="Year-to-date return")

    # Analysis
    key_events: list[str] = Field(default_factory=list, description="Key events")
    market_commentary: str = Field(default="", description="Market commentary")
    outlook: str = Field(default="", description="Outlook")

    # Daily breakdown
    daily_summaries: list[dict[str, Any]] = Field(
        default_factory=list, description="Daily summaries"
    )


class MonthlyReport(BaseModel):
    """Monthly comprehensive report."""

    metadata: ReportMetadata = Field(..., description="Report metadata")
    month: int = Field(..., description="Month")
    year: int = Field(..., description="Year")

    # Summary sections
    nav_summary: NavSummary = Field(..., description="NAV summary")
    flow_summary: FlowSummary = Field(..., description="Flow summary")
    risk_summary: RiskSummary = Field(..., description="Risk summary")
    allocation_summary: AllocationSummary = Field(..., description="Allocation summary")

    # Performance comparison
    monthly_return: Decimal = Field(..., description="Monthly return")
    benchmark_return: Decimal = Field(..., description="Benchmark return")
    alpha: Decimal = Field(..., description="Alpha vs benchmark")
    sharpe_ratio: Decimal = Field(..., description="Sharpe ratio")
    max_drawdown: Decimal = Field(..., description="Max drawdown")

    # Detailed analysis
    performance_attribution: dict[str, Decimal] = Field(
        ..., description="Performance attribution"
    )
    risk_metrics: dict[str, Decimal] = Field(..., description="Risk metrics")

    # Recommendations
    recommendations: list[str] = Field(
        default_factory=list, description="Recommendations"
    )

    # Weekly breakdown
    weekly_summaries: list[dict[str, Any]] = Field(
        default_factory=list, description="Weekly summaries"
    )


class StoredReport(BaseModel):
    """Stored report reference."""

    report_id: str = Field(..., description="Report ID")
    report_type: ReportType = Field(..., description="Report type")
    period_start: date = Field(..., description="Period start")
    period_end: date = Field(..., description="Period end")
    format: ExportFormat = Field(..., description="Format")
    status: ReportStatus = Field(..., description="Status")
    storage_path: str = Field(..., description="Storage path")
    file_size_bytes: int = Field(..., description="File size")
    created_at: datetime = Field(..., description="Created at")
    download_url: str | None = Field(None, description="Download URL")
